---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: ''
  label: Blog
  create: documents
  match: examples/docs/content/**/*
  templates:
  - blog-post
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - AIRTABLE_TOKEN=keyxXWnci3b1xXdre
  preview_output_directory: examples/docs/dist
  install_dependencies_command: cd examples/docs && npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run build
